### ISSUE TITLE
SoD PureITA su OSMC su rPi3

### ISSUE THREAD

**Issue by gerrydoro** [orione7/plugin.video.streamondemand-pureita#1]
Ciao, ho appena installato la tua estensione su OSMC sul mio Raspberry Pi 3, appena la avvio però mi da "Errore, controlla i log per ulteriori informazioni" ma a quanto vedo i log sono vuoti. Può darsi che manchi qualche dipendenza? Sto usando l'ultimissima versione di OSMC installata proprio oggi (2017/06/19)

**Comment by orione7** [comment]
Ciao, prova a cambiare la skin in confluence

**Comment by gerrydoro** [comment]
Ok oggi provo grazie <3
