### ISSUE TITLE
Wstream e AKVideo/AKStream vanno ?

### ISSUE THREAD

**Issue by DjDiabolik** [orione7/plugin.video.streamondemand-pureita#11]
In questo PureITA ? Nel SOD "normale" no.........e non saranno fixati.

**Comment by DjDiabolik** [comment]
Posto qualche info su un possibile test...............

Prendete qualsiasi mirror dal sito CB01.uno.........esempio questo:
https://www.cb01.zone/il-re-della-polka-hd-2017/

Prendete quindi uno dei mirror in HD......... sono appunto 4:
Akvideo (o a volte è Akstrem... ma è praticamente lo stesso sito su 2 mirror diversi..)
OpenLoad
Streamango
Wstream

Come detto su Wstream si arriva alla finestra dove dice "Guarda Mp4". Poi dai Ok e si ritorna alla lista dei mirror e non parte niente.
Su AkVideo invece va in errore subito............. come dico sopra i mirror sono 2.
Akvideo e Akstream....... esattamente lo stesso video solo che uno è:
Akvideo.stream e l'altro è Akstream.video.............

**Comment by orione7** [comment]
I server nei canali ritenuti importanti per l'utilizzo di quest'ultimi sono tutti aggiornati  se ci sono eventuali  server non funzionanti e che richiedono un cambio di versione verranno aggiornati nella prossima release se verra ritenuto importante. Per quanto riguarda invece i canali questi invece vengono aggiornati quotidianamente con gli autoupdate.

**Comment by DjDiabolik** [comment]
@orione7 aspetta aspetta.
Ma quindi l'autoupdate riguarda solo i canali ? Io sapevo, e magari sbagliavo, che anche i server venissero aggiornati ?
