### ISSUE TITLE
Majintoon

### ISSUE THREAD

**Issue by mattitotti96** [orione7/plugin.video.streamondemand-pureita#14]
Buonasera a tutti, per favore potete sistemare majintoon non tutti cartoni si vedono... alcuni ci sono i link per vederli e alcuni dice che la playlist e vuota quando invece non è vero...

**Comment by orione7** [comment]
Fixed

**Comment by falcorn87** [comment]
I tried Majintoon to watch One Piece HD but only wstream link works. 
SOD show blank list on UpVid and FlashX. 
Some Wstream link doesn't work
