### ISSUE TITLE
compatibilità con Plex

### ISSUE THREAD

**Issue by croccio** [orione7/plugin.video.streamondemand-pureita#2]
per caso c'è la possibilità di installarlo su Plex?

**Comment by orione7** [comment]
Ciao, con il rientro dalle vacanze da parte di alcuni dello staff me compreso, ci siamo messi al lavoro riprendendo il completamento di un progetto che include il lancio di un pacchetto di release inedite compatibile con tutte le piattaforme e per tutti (o quasi) device. Chiediamo soltanto un po' di pazienza

**Comment by DarkLegend11** [comment]
A me con l'ultimo aggiornamento l'addon non funziona più!! 😔
