### ISSUE TITLE
Chiede sempre di essere aggiornato... perchè ?

### ISSUE THREAD

**Issue by DjDiabolik** [orione7/plugin.video.streamondemand-pureita#21]
La domanda è nel titolo seppur parzialmente.......... 
In pratica ho notato che è stata rilasciata questa 5.4.9 e mi è stato chiesto se volessi aggiornare e cosi ho fatto.
Ho riavviato, nel mio caso, il mio Raspberry e seppur nelle info dell'addons mi dice che è correttamente installata la 5.4.9 ogni volta che lo avvio mi risuggerisce di fare l'aggiornamento ogni volta.

Normale ?

**Comment by orione7** [comment]
Prova a fare un'aistallazione pulita dell'addon
