### ISSUE TITLE
[Domanda] Versione mediaserver

### ISSUE THREAD

**Issue by gerrydoro** [orione7/plugin.video.streamondemand-pureita#3]
Salve, mi chiedevo se su questo repository posso trovare anche la versione Mediaserver di SoD, in particolare quella compatibile con WiiMC (quindi suppongo quella senza la versione HTML "grafica")
Grazie.

**Comment by orione7** [comment]
Ciao, con il rientro dalle vacanze da parte di alcuni dello staff me compreso, ci siamo messi al lavoro riprendendo il completamento di un progetto  che include  il lancio di un pacchetto di release inedite compatibile con  tutte le piattaforme e per tutti (o quasi) device. Chiediamo soltanto un po' di pazienza
