### ISSUE TITLE
Selezione su risultati della ricerca non funzionanti su Android TV

### ISSUE THREAD

**Issue by LBRDan** [orione7/plugin.video.streamondemand-pureita#7]
Dopo il click di un risultato della ricerca film, si blocca e non ottiene risultati su Android TV. Su Pc linux/Windows funziona perfettamente lo stesso film/risultato

16:00:24.846 T:18446744072941996336   ERROR:     [streamondemand-pureita-master.ffilms.search] <traceback object at 0xd1b881e8>
16:00:24.923 T:18446744072953198896   ERROR: ######## ERROR #########
16:00:24.923 T:18446744072953198896   ERROR:     [streamondemand-pureita-master.channels.biblioteca.worker] Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand-pureita-master/channels/biblioteca.py", line 623, in worker
                                                channel_result_itemlist.extend(obj.search(Item(extra=item.url), tecleado))
                                            AttributeError: 'module' object has no attribute 'search'

Allego link a log di sistema
Android TV
Kodi 14.4

Inoltre se si prova ad uscire totalmente da Kodi, si freeza e fa forzata la chiusura dalle impostazioni di Android

Passi per riprodurre
Ricerca "cars"
Selezionare il risultato "Cars 3"

http://paste.ubuntu.com/25785574/

**Comment by orione7** [comment]
Quale skin hai installato in Kodi?

**Comment by LBRDan** [comment]
Confluence

**Comment by LBRDan** [comment]
Ho provato con altro Android TV, con lo stesso procedimento stesso risultato. C'è qualcosa che non va in quella specifica entry.
Inoltre ho notato che mentre su PC Windows e Linux non da problemi e mostra i risultati da tutte le fonti, su Android TV si ha un blocco interfaccia che solo a volte si sblocca mostrando un solo risultato

**Comment by orione7** [comment]
quale versione di kodi hai installato?
