### ISSUE TITLE
Risultati ricerche incomplete

### ISSUE THREAD

**Issue by Gencix** [orione7/plugin.video.streamondemand-pureita#8]
Salve, segnalo che alcune ricerche ( es. casacinema) non restituiscono risultati completi (con le serie)

**Comment by orione7** [comment]
device e versione di kodi?

**Comment by Gencix** [comment]
Con Kodi aggiornato all'ultima versione (ma succedeva anche con le precedenti) e Tema Confluence,
Sia con Tvbox Android 6 che Cellulare Android 7

**Comment by orione7** [comment]
mi fai un esempio concreto nome della serie e canale

**Comment by Gencix** [comment]
Sul canale "casacinema"
Utilizzando "factor" per trovare gli episodi di xfactor
Da SOD pure ita non visualizza gli ultimi episodi dei Live ( ci sono solo daily e xtrafactor)
Mentre sul sito da browser ci sono. Sono divisi in prima parte e seconda parte ed in qualità molto buona, potrebbe dipendere da questo?

Guardando l'html della pagina in questione ho notato che il tag "<a" che contiene il link dei live, contrariamente agli altri della lista è preceduto da una parentesi "(" 
Potrebbe dipendere dal dover modificare nel file py di cascinema la regola?

**Comment by orione7** [comment]
Ciao, scusa ma ho notato solo adesso. Il problema descritto  e circoscritto solo per Xfactor oppure hai trovato altre anomalie?

**Comment by Gencix** [comment]
Ho notato questo perché cercato di recente, per altri non avevo fatto caso

**Comment by orione7** [comment]
Fixed

**Comment by orione7** [comment]
Fixed
