### ISSUE TITLE
 EXCEPTION: XML File for Window is missing

### ISSUE THREAD

**Issue by ildeb** [orione7/plugin.video.streamondemand-pureita#9]
Salve,
il plugin va in crash a causa di un file XML mancante, qui di seguito una parte del file kodi.log:

23:40:09.120 T:3019395072  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 29.970032 Hz
23:40:09.120 T:3019395072  NOTICE: Found (1920x1080@60.000000) at 48, setting to RES_DESKTOP at 16
23:40:09.121 T:3019395072  NOTICE: Checking resolution 49
23:40:09.518 T:3019395072  NOTICE: GL_VENDOR = Broadcom
23:40:09.518 T:3019395072  NOTICE: GL_RENDERER = VideoCore IV HW
23:40:09.518 T:3019395072  NOTICE: GL_VERSION = OpenGL ES 2.0
23:40:09.518 T:3019395072  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
23:40:09.519 T:3019395072  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 
GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_mapbuffer GL_EXT_textu
re_format_BGRA8888 GL_APPLE_rgb_422 GL_EXT_debug_marker
23:40:12.753 T:2889208752  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
23:40:12.852 T:2931811248  NOTICE: Running database version Addons27
23:40:12.858 T:2931811248  NOTICE: Running database version ViewModes6
23:40:12.873 T:2931811248  NOTICE: Running database version Textures13
23:40:12.896 T:2931811248  NOTICE: Running database version MyMusic60
23:40:12.943 T:2931811248  NOTICE: Running database version MyVideos107
23:40:12.952 T:2931811248  NOTICE: Running database version TV29
23:40:12.965 T:2931811248  NOTICE: Running database version Epg11
23:40:12.975 T:3019395072  NOTICE: start dvd mediatype detection
23:40:15.020 T:3019395072 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
23:40:17.073 T:3019395072  NOTICE: initialize done
23:40:17.074 T:3019395072  NOTICE: Running the application...
23:40:17.158 T:3019395072  NOTICE: starting zeroconf publishing
23:40:17.159 T:3019395072  NOTICE: starting upnp client
23:40:17.232 T:2735993776  NOTICE: ES: Starting UDP Event server on port 9777
23:40:17.239 T:2735993776  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
23:43:43.643 T:2794976176 WARNING: CSkinInfo: failed to load skin settings
23:43:43.664 T:2794976176   ERROR: EXCEPTION: XML File for Window is missing
23:43:43.673 T:2794976176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 50, in <module>
                                                window = navigation.get_window_for_item( item )
                                              File "/home/pi/.kodi/addons/plugin.video.streamondemand-pureita-master/navigation.py", line 294, in get_window_for_item
                                                window = window_channels.ChannelWindow("banner.xml",plugintools.get_runtime_path())
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--

**Comment by orione7** [comment]
Ciao, Installa la versione 5.4.6
